### ISSUE TITLE
Can't fork optimism mainnet

### ISSUE THREAD

**Issue by pandadefi** [ApeWorX/ape-optimism#22]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.7.4
 
$ ape plugins list
 
Installed Plugins
  etherscan 0.7.0
  foundry 0.7.2
  optimism 0.7.0
  solidity 0.7.1
```

* Python Version: 3.10.12
* OS: macOS

```
File: ape-config.yaml
name: auto-op
plugins:
  - name: optimism
  - name: etherscan
  - name: foundry
  - name: solidity
 
default_ecosystem: optimism
 
optimism:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry
```

### What went wrong?

```
ape test --network optimism:mainnet-fork
```

it is not possible to fork the optimism chain.

```
INTERNALERROR> ape.exceptions.BlockNotFoundError: Block with ID '0' not found. Reason: The field extraData is 117 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer to http://web3py.readthedocs.io/en/stable/middleware.html#proof-of-authority for more details. The full extraData is: HexBytes('0x000000000000000000000000000000000000000000000000000000000000000000000398232e2064f896018496b4b44b3d62751f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000')
```

### How can it be fixed?
